declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

export const ROUTES = {
  home: MAIN_WINDOW_WEBPACK_ENTRY,
};

export const PRE_LOAD_URL = MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY;
